include:
- sample.zip
kind: ArchiveUploadSpec
name: sample-zip-Nu08

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fissionzapier-pkg
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sample-zip-Nu08
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-04-07T08:59:50Z"
