include:
- sample.zip
kind: ArchiveUploadSpec
name: sample-zip-Er1W

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fissionzapier-pkg
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sample-zip-Er1W
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-04-08T05:34:51Z"
