apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: pawesome
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: pawesome
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /pawesome
    tls: ""
  method: ""
  methods:
  - POST
  - GET
  prefix: /pawesome
  relativeurl: ""
