
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: aws-credentials
stringData:                     # note that we are using string data, and not base64 encoded data
  awsAccessKeyID: aws-access-key-id
  awsSecretAccessKey: aws-secret-access-key
type: Opaque

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: stream-details
data:
  AWS_REGION: us-east-2
