include:
- kafka-producer/*
kind: ArchiveUploadSpec
name: kafka-producer-CPht

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: producer-28afb578-6fed-48d1-89bf-7590dc662414
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://kafka-producer-CPht
status:
  buildstatus: pending
  lastUpdateTimestamp: "2021-06-10T17:35:09Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: producer
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: Handler
    packageref:
      name: producer-28afb578-6fed-48d1-89bf-7590dc662414
      namespace: default
  requestsPerPod: 1
  resources: {}
  secrets: null
