include:
- k-consumer.js
kind: ArchiveUploadSpec
name: k-consumer-js-o2Io

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: k-consumer-c34f7910-4226-4217-b2b9-29204abd5d0d
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://k-consumer-js-o2Io
  environment:
    name: nodeenv
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2021-06-11T03:47:16Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: k-consumer
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps: null
  environment:
    name: nodeenv
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: k-consumer-c34f7910-4226-4217-b2b9-29204abd5d0d
      namespace: default
  requestsPerPod: 1
  resources: {}
  secrets: null
