apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hellojs
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps: null
  environment:
    name: node
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: hellojs
      namespace: default
  requestsPerPod: 1
  resources: {}
  secrets: null
